# Generated by Django 2.1.5 on 2019-04-23 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reccomend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingitem',
            name='colthing_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
