# Generated by Django 2.1.5 on 2019-04-23 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reccomend', '0003_auto_20190423_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('colthing_bust', models.IntegerField(blank=True, null=True)),
                ('colthing_size', models.CharField(max_length=50)),
                ('body_shape', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='clothingitem',
            name='colthing_size',
        ),
        migrations.RemoveField(
            model_name='clothingitem',
            name='description_text',
        ),
        migrations.RemoveField(
            model_name='ratings',
            name='score_val',
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='event_type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ratings',
            name='body_shape',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ratings',
            name='colthing_bust',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ratings',
            name='colthing_size',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ratings',
            name='rating_val',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ratings',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
