# Generated by Django 2.1.5 on 2019-04-29 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reccomend', '0005_auto_20190429_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingitem',
            name='img_url',
            field=models.CharField(default='https://pc-ap.rtrcdn.com/productimages/nomodel/1080x/07/BH77.jpg', max_length=200),
            preserve_default=False,
        ),
    ]
