# Generated by Django 2.1.5 on 2019-05-02 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reccomend', '0008_auto_20190501_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingitem',
            name='avg_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating_val',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='colthing_bust',
            field=models.CharField(max_length=5),
        ),
    ]
